export enum NodeDiscriminator {
  IDENTIFIED_NODE = 'IDENTIFIED_NODE',
  TYPED_NODE = 'TYPED_NODE',
  GROUP_NODE = 'GROUP_NODE',
  NON_DESCRIBED_NODE = 'NON_DESCRIBED_NODE',
  DESCRIBED_NODE = 'DESCRIBED_NODE',
}
